# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool: websitevmssagents

steps:
- checkout: self
  submodules: true
- script: |
    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh get-docker.sh
    sudo groupadd docker
    sudo usermod -aG docker $USER
    newgrp docker
  displayName: 'Install Docker'
- task: AzureStaticWebApp@0
  inputs:
    app_location: 'src/website'
    #api_location: ''
    #skip_app_build: true
    skip_api_build: true
    output_location: 'src/infrastructure'
    azure_static_web_apps_api_token: $(deployment_token)

