# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool: 
  vmImage: ubuntu-latest

variables: 
  - group: static-website-variables
  
steps:
- checkout: self
# 3 tasks: 1.) download + install terraform, 2.) initialize + plan 3.) run terraform apply
# Download file from download link: https://releases.hashicorp.com/terraform/1.6.4/terraform_1.6.4_linux_amd64.zip
# Extract file
# Move file into /usr/local/bin/terraform
- script: |
    wget -nv "https://releases.hashicorp.com/terraform/1.6.4/terraform_1.6.4_linux_amd64.zip"
    unzip terraform_1.6.4_linux_amd64.zip
    mv -v terraform /usr/local/bin
    terraform -v
  displayName: Install Terraform
# Azure CLI v2
# Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
- task: AzureCLI@2
  displayName: Initialize & Plan Terraform
  inputs:
    azureSubscription: AZLabConnection # string. Alias: connectedServiceNameARM. Required. Azure Resource Manager connection. 
    scriptType: bash # 'ps' | 'pscore' | 'batch' | 'bash'. Required. Script Type. 
    scriptLocation: inlineScript # 'inlineScript' | 'scriptPath'. Required. Script Location. Default: scriptPath.
    #scriptPath: # string. Required when scriptLocation = scriptPath. Script Path. 
    # string. Required when scriptLocation = inlineScript. Inline Script.
    inlineScript: |
      terraform init
      terraform plan
    #arguments: # string. Alias: scriptArguments. Script Arguments. 
    #powerShellErrorActionPreference: 'stop' # 'stop' | 'continue' | 'silentlyContinue'. Optional. Use when scriptType = ps || scriptType = pscore. ErrorActionPreference. Default: stop.
  # Advanced
    addSpnToEnvironment: true # boolean. Access service principal details in script. Default: false.
    #useGlobalConfig: false # boolean. Use global Azure CLI configuration. Default: false.
    workingDirectory: ./src/infrastructure/web-app # string. Alias: cwd. Working Directory. 
    #failOnStandardError: false # boolean. Fail on Standard Error. Default: false.
    #powerShellIgnoreLASTEXITCODE: false # boolean. Optional. Use when scriptType = ps || scriptType = pscore. Ignore $LASTEXITCODE. Default: false.
# Manual validation v0
# [PREVIEW] Pause a pipeline run to wait for manual interaction. Works only with YAML pipelines.
- task: ManualValidation@0
  displayName: Approve Terraform Apply
  inputs:
    #notifyUsers: # string. Required. Notify users. 
    instructions: Check plan and approve if good # string. Instructions. 
    #onTimeout: 'reject' # 'reject' | 'resume'. On timeout. Default: reject.