# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool: 
  vmImage: ubuntu-latest

variables: 
  - group: static-website-variables
  
steps:
- checkout: self
# 3 tasks: 1.) download + install terraform, 2.) initialize + plan 3.) run terraform apply
# Download file from download link: https://releases.hashicorp.com/terraform/1.6.4/terraform_1.6.4_linux_amd64.zip
# Extract file
# Move file into /usr/local/bin/terraform
- script: |
    wget -nv "https://releases.hashicorp.com/terraform/1.6.4/terraform_1.6.4_linux_amd64.zip"
    unzip terraform_1.6.4_linux_amd64.zip
    mv -v terraform /usr/local/bin
    terraform -v